   bar {
       status_command i3status
        colors {
  # class                 border  backgr. text    indicator
  focused_workspace          #a3b38c #d65d0e #1a1826 #a3b38c
  active_workspace #e5e9f0 #5f676a #ffffff #e5e9f0
  inactive_workspace        #333333 #222222 #888888 #292d2e
  urgent_workspace      #cc241d #900000 #ffffff #cc241d
  binding_mode   #000000 #0c0c0c #ffffff #000000
  
             background #282A2E
       }
       position top
   }
